from g_exception.excepiton_handler import g_except_config

# print(a)
pass